### ISSUE TITLE
landscape mode setting?

### ISSUE THREAD

**Issue by max-mapper** [bfabiszewski/kterm#1]
Hiya, is there any way to force landscape mode on launch?

**Comment by bfabiszewski** [comment]
UPDATE: Kterm supports landscape mode natively since version 2.0.

**Comment by 9600** [comment]
How do you enable landscape mode on a PW3?

**Comment by bfabiszewski** [comment]
From menu (pops up on two fingers click) you choose "Screen rotate". Or, if you want to start in landscape mode, you must add `-o R` argument on command line.
