### ISSUE TITLE
kterm not working on kindle voyage at all

### ISSUE THREAD

**Issue by tarungupta2001** [bfabiszewski/kterm#13]
Kterm is not working on a jailbroken kindle voyage from kual.On tapping kterm entry in kual, it returns to home screen and nothing happens.

**Comment by bfabiszewski** [comment]
Difficult for me to reproduce it as I don't have Voyage.

It would be helpful if you could connect to your device via ssh and start kterm from command line. There might be some error messages which will help solve the problem.

**Comment by tarungupta2001** [comment]
Sir i uninstalled and reinstalled.now working properly

On Tue, Aug 1, 2017 at 5:47 PM, Bartek Fabiszewski <notifications@github.com

**Comment by bfabiszewski** [comment]
Great!
