### ISSUE TITLE
Canot Run As Root

### ISSUE THREAD

**Issue by seelyowen** [bfabiszewski/kterm#14]
It wouldbe verry nice if you could run as root to intall the files you made for us to install. I probably rent doing something right but please get sudo or tessus how to.

**Comment by seelyowen** [comment]
Also I'm running kterm 2.4 on a kindle paperwhite.

**Comment by bfabiszewski** [comment]
This is beyond the scope of kterm issue tracker. 
Please try to get help at[ Kindle Developer's Corner](https://www.mobileread.com/forums/forumdisplay.php?f=150).
