### ISSUE TITLE
unable to build on ubuntu

### ISSUE THREAD

**Issue by max-mapper** [bfabiszewski/kterm#2]
hello,

I installed `libvte-dev` on ubuntu and then did `make`, which told me it couldn't find `lib/libvte.a`, so I edited the `Makefile` and used `LIBVTE=-lvte`

doing `make` the second time threw the error `/usr/bin/ld: cannot open output file bin/kterm: No such file or directory`, so I did `mkdir bin` and ran `make again`:

``` bash
gcc kterm.c parse_config.c -lvte -O2 -Wall `pkg-config --cflags --libs gtk+-2.0 glib-2.0` -ltermcap -o bin/kterm
kterm.c: In function ‘launch_keyboard’:
kterm.c:98: warning: ignoring return value of ‘pipe’, declared with attribute warn_unused_result
kterm.c:99: warning: ignoring return value of ‘pipe’, declared with attribute warn_unused_result
kterm.c:106: warning: ignoring return value of ‘dup’, declared with attribute warn_unused_result
```

I tried putting the resulting binary `kterm` onto my kindle but it never launches. The binary I downloaded from your website was ~600kb whereas the one I built was ~35kb. Am I missing a step?

**Comment by nkwsy** [comment]
Is there a way to make this build work with the Pw3?

**Comment by bfabiszewski** [comment]
I don't have PW3 but some users reported that it works on this device. You may try to get help at [Kindle Developer's Corner](http://www.mobileread.com/forums/forumdisplay.php?f=150).
