### ISSUE TITLE
Can't rotate screen?

### ISSUE THREAD

**Issue by aleemont** [bfabiszewski/kterm#21]
Can't see the option to rotate screen in the Menu (activated with 2 fingers tap in kterm)?

**Comment by bfabiszewski** [comment]
Probably your kterm was built without `--enable-kindle` option. See [building instructions](https://github.com/bfabiszewski/kterm#building).

**Comment by aleemont** [comment]
I downloaded the .zip file and unzipped it in my extensions folder in kindle. So i need to remove it and build the bin myself in order to be able to rotate screen?

**Comment by bfabiszewski** [comment]
Please post download link. 
If it is my build, I will try to fix it.

**Comment by aleemont** [comment]
https://github.com/bfabiszewski/kterm/releases/tag/v2.6

**Comment by bfabiszewski** [comment]
This build should be fine. Maybe the lower part of the menu is cropped by the screen and you can't see it?
Could you post screenshot?

**Comment by aleemont** [comment]
Tried to build package, now kterm is not startind on Kindle.
This is exactly what i did:

Removed old kterm folder from extensions dir.

`yay -S vte`
`sudo pacman -S dbus`
`git clone https://github.com/bfabiszewski/kterm`
`cd kterm`
`./autogen.sh`
`./configure --enable-kindle --sysconfdir=/mnt/us/extensions/kterm`
`sudo make dist-kindle`

Mounted Kindle
Uploaded .zip file in extensions dir, unzipped it
Unmounted Kindle

**Comment by aleemont** [comment]
[SOLVED]
Downloaded package again, I may have pick a wrong version last time. Now It is working. Sorry for bothering you. You should also check my last comment, cuz that didn't work

**Comment by bfabiszewski** [comment]
Nice.
Regarding your problems there must be something wrong with the package you created. Compare it with original working one. Regarding compilation, it can be tricky. Remember you should cross compile for proper arm architecture.
