### ISSUE TITLE
Link for x11vnc is broken

### ISSUE THREAD

**Issue by plredmond** [bfabiszewski/kterm#23]
Your pre-compiled packages webpage (http://www.fabiszewski.net/kindle-terminal/) has a link for _x11vnc_ which gets a "zip file" which is actually an html document:
```html
<html>
  <head><title>Found</title></head>
  <body>
    <h1>Found</h1>
    <p>The resource was found at <a href="https://dl.dropboxusercontent.com/s/ahidr95vfjhx0vn/x11vnc.zip?dl=1">https://dl.dropboxusercontent.com/s/ahidr95vfjhx0vn/x11vnc.zip?dl=1</a>;
you should be redirected automatically.

<!--  --></p>
    <hr noshade>
    <div align="right">WSGI Server</div>
  </body>
</html>
```
Following the dropbox link therein is a 403.

**Comment by bfabiszewski** [comment]
Please try this one:
[x11vnc.zip](https://github.com/bfabiszewski/kterm/files/6372345/x11vnc.zip)

**Comment by plredmond** [comment]
Thank you!

BTW, did you set up your compiler toolchain on a VM using the ancient ubuntu version the kindle describes in its GPL disclosures?

**Comment by bfabiszewski** [comment]
I took similar approach. I created a filesystem from Debian packages based on what is on real Kindle. Then I set up cross compiler to use this root filesystem.
