### ISSUE TITLE
Where to put binaries? or which file to edit to add custom $PATH?

### ISSUE THREAD

**Issue by gotbletu** [bfabiszewski/kterm#24]
downloaded elinks, wget, tmux, vim ...etc from http://www.fabiszewski.net/kindle-terminal/

i put them in
`Kindle:/extensions/kterm/bin/`

how you make it load up all those programs to the $PATH?

i tryed
```
vim kterm.sh
export PATH="/mnt/us/extensions/kterm/bin:$PATH"
export PATH="$EXTENSION/bin:$PATH"
export PATH="/bin:$PATH"
```

but doesnt work

i have to manually execute commands locally or give path to binary to use it, kind of annoying
```
cd /bin
./elinks
```

**Comment by bfabiszewski** [comment]
These variables are not inherited by the shell run within kterm.
You could try `kterm -E` option which sets environmental variable.

**Comment by gotbletu** [comment]
tried these does not seem to work
```
./kterm -E

./kterm -E ./kterm.sh

./kterm.sh

./kterm ./kterm.sh

# does not update $PATH
echo $PATH
```

**Another question**: how did you cross compile those ARM packages (tmux, elinks..etc for kindle)?
was it using a VM or can i just use my x64 linux system. Thanks

**Comment by bfabiszewski** [comment]
You should specify the variable as an argument to `-E` option.
Something like this:
`kterm -E PATH="/mnt/us/extensions/kterm/bin:$PATH"`

**Comment by bfabiszewski** [comment]
I was cross compiling. You will need proper toolchain built for Kindle environment. I set up my system long time ago using tools that are no longer maintained. But there are many modern ways to go. 
You can get help at [Kindle Developer's Corner](https://www.mobileread.com/forums/forumdisplay.php?f=150).

**Comment by gotbletu** [comment]
`kterm -E PATH="/mnt/us/extensions/kterm/bin:$PATH"`
ok that works

Thanks again for all the info
