### ISSUE TITLE
Encoding for Cyrillic Characters

### ISSUE THREAD

**Issue by mergen3107** [bfabiszewski/kterm#28]
Hi @bfabiszewski 
Thank you very much for kterm! 
I used it on PW3, and now use it on Kindle Scribe. 

Works like a charm!
How many times it saved my KOReader builds that I patched wrong :D 

Do you know if kterm can show Cyrillic characters?

For example, `ls` now shows Russian letters as `?`. 

Thank you!

**Comment by bfabiszewski** [comment]
Hi, glad that you find ktem useful!

Regarding your issue, kterm should handle cyrillic encoding, as we already [discussed it before](https://github.com/bfabiszewski/kterm/pull/15).
There may be many problems though. There may be an issue with `ls` command itself, issue with a font, issue with filename encoding.
Try to use `find . -maxdepth 1` instead of `ls`.
Try to find out how the filenames are encoded. Each OS has its own filename encoding. I am not sure what happens when you copy those files to kindle.

**Comment by mergen3107** [comment]
Thank you! I'll have a look

Sorry, I forgot that we discussed it here :D 
I was looking for my question all over MobileRead

**Comment by mergen3107** [comment]
> find . -maxdepth 1

This worked great! Thank you!

Now all I need to do is to change the alternative keyboard layout in kterm to be able to grep books in Cyrillic :D 

(And I guess, `ls` belongs to Kindle's `bash`, but I don't know how to use replace by a more up-to-date shell...)

**Comment by mergen3107** [comment]
Correction:
```
readlink /bin/ls
```
revealed that it points to `busybox, which is also in `/bin` folder.

**Comment by bfabiszewski** [comment]
Probably busybox is built without unicode support?

**Comment by mergen3107** [comment]
I vaguely remember that old ones did have problems with encoding, but I can't find it where I saw it

**Comment by mergen3107** [comment]
@bfabiszewski 
(Can I please also ask about Leafpad here?

On my Kindle Scribe FW 5.16.2 and 5.16.2.0.1 when I tap on top menus (File, etc), keyboard disappears. I can see leftovers from KUAL interface. When I tap on the text area, keyboard doesn't come back)

**Comment by bfabiszewski** [comment]
Keyboard is opened by calling `/usr/bin/lipc-set-prop` binary. Maybe it does not exist in your firmware. Or has different behavior. 
Exact command is: `execlp("/bin/sh", "sh", "-c", "/usr/bin/lipc-set-prop -s com.lab126.keyboard open net.fabiszewski.leafpad:Abc:1", NULL);`

TBH I am surprised it works at all with different firmware. Those ports were pure hacks.

**Comment by mergen3107** [comment]
Thank you very much! I'll have a closer look

**Comment by mergen3107** [comment]
I tried this exact command and it works!
```
/usr/bin/lipc-set-prop -s com.lab126.keyboard open net.fabiszewski.leafpad:Abc:1
```

**Comment by mergen3107** [comment]
It actuall also works in kterm, but it covers the screen. I was actually able to type "exit" and hit enter to quit. Keyboard stayed, but then I went to Kindle Search and back, and it disappeared

**Comment by bfabiszewski** [comment]
So I don't know why it does not open from Leafpad

**Comment by mergen3107** [comment]
Thank you very much in any case!
Your work from 5-7 years ago still holds up, and I am grateful to you :)
