### ISSUE TITLE
Request for the static library "libvte.a"

### ISSUE THREAD

**Issue by cdhigh** [bfabiszewski/kterm#29]
Could you kindly please add the static library `libvte.a` to the repository? 
I successfully set up a cross-compilation environment for Kindle on Ubuntu and have conducted tests on the Kindle device using simple command-line and GTK GUI programs.

While I managed to compile kterm, the resulting binary is only around 200 KB, whereas yours is over 600 KB. After reviewing historical issues, I discovered that the difference lies in the need for static linking with `libvte`. However, despite two days of effort, I couldn't successfully compile `libvte.a` for the armv7a architecture.

I wonder if you might still have a backup of this library on your machine. If you could upload it to the repository, I would greatly appreciate it.

I understand that libvte.a is tied to a specific version of GLib, but finding a compatible GLib version shouldn't be too challenging.

**Comment by bfabiszewski** [comment]
I was bundling static lib to facilitate my binary distribution for Kindle users. You can also try to use dynamic library, but you will have to copy it to Kindle filesystem.
For the static library you may try to use Debian version. I think I was using some prebuilt binaries from Squeeze. It is no longer available in package manager, but still exists in Debian archive. Have a look for example at [this directory](https://snapshot.debian.org/archive/debian/20121231T212057Z/pool/main/v/vte/). The interesting file is `libvte-dev_0.24.3-4_armel.deb`. If this version is too new look at older snapshots in the archive.

**Comment by cdhigh** [comment]
Thank you so much for your helpful suggestions. 
After another day of struggling, I finally succeeded in compiling kterm and running it on my Kindle.  
Kterm is an amazing project.  
Once again, thank you very much!

**Comment by bfabiszewski** [comment]
Thanks, glad that it works!
