### ISSUE TITLE
This is cannot work on my kindleBasic version 5.6.5

### ISSUE THREAD

**Issue by DreamLiMu** [bfabiszewski/kterm#5]
I just apply the new version kterm on my KindleBasic,but it does'nt work. My kindle version is 5.6.5 and have jailbreaked. Thank you for reply me!

**Comment by bfabiszewski** [comment]
I know that some libraries were upgraded in 5.6.5 firmware. That is why some binaries compiled for old firmwares will not start. I don't have a device with the new firmware but I believe the problem with kterm is related to matchbox-keyboard binary being linked to old libpng library. Could you please check if [this kterm](http://www.fabiszewski.net/kindle-terminal/kterm-0.7-5.6.5.zip) package fixes the problem?

**Comment by DreamLiMu** [comment]
Thank you for reply me, but it dose'nt work!

**Comment by bfabiszewski** [comment]
To solve this problem you would have to log in to your kindle through ssh and try to start kterm and matchbox-keyboard binaries from the above package manually from command line. Then you would be able to see what the exact error is. Otherwise I can't do anything, as I don't have this firmware version. Maybe some other libraries are still missing, or there is another problem.

**Comment by DreamLiMu** [comment]
OK! I will try it tonigiht. Thanks!

**Comment by DreamLiMu** [comment]
the error pic.
![snip20151113_1](https://cloud.githubusercontent.com/assets/8113651/11146726/bd96608e-8a4b-11e5-9b78-db286b466406.png)

**Comment by bfabiszewski** [comment]
Thank you for the report. There still seems to be a problem with libpng. Maybe it would be a better solution to statically link to the old version of the library. Please try the [new package](http://www.fabiszewski.net/kindle-terminal/kterm-0.7-5.6.5-2.zip).

**Comment by DreamLiMu** [comment]
Ok! It work well, so beautiful. Thanks very much! Great!

**Comment by bfabiszewski** [comment]
Thanks for your help to solve it out!
