### ISSUE TITLE
Does kterm support kindle voyage ?

### ISSUE THREAD

**Issue by zhoujiealex** [bfabiszewski/kterm#8]
I've used  this plugin two year ago in my  kindle papaerwhite 2.
It worked very well.

Recently, I try to use it in kindle voyage which failed.

My question is how to use it in kindle voyage, or is it possible ?

**Comment by bfabiszewski** [comment]
I don't have voyage, but I vaguely remember someone on [mobileread](https://www.mobileread.com/forums/forumdisplay.php?f=150) mentioning using kterm on the device.
If you log in to your kindle through ssh and start kterm from command line, you may see some error messages that will tell us more.

**Comment by bfabiszewski** [comment]
I am closing this issue. If you can provide more details, please reopen it.
